services:
  db:
    image: postgres:15
    container_name: http-postgres-db
    restart: always
    environment:
      POSTGRES_DB: http_scraper_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - http_pgdata:/var/lib/postgresql/data
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  scraper-app:
    build:
      context: .
    restart: unless-stopped
    container_name: http-webscraper-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATASOURCE_URL: jdbc:postgresql://db:5432/http_scraper_db
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: pass
    ports:
      - "8080:8080"
    env_file: src/main/resources/.env

volumes:
  http_pgdata: