services:
  db:
    image: postgres:15
    container_name: http-postgres-db
    restart: always
    environment:
      POSTGRES_DB: http_scraper_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - http_pgdata:/var/lib/postgresql/data
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql

  scraper-app:
    build:
      context: .
    container_name: http-webscraper-app
    depends_on:
      - db
    environment:
      DATASOURCE_URL: jdbc:postgresql://db:5432/http_scraper_db
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: pass
      GRAPH_QL_URL: https://999.md/graphql
      GRAPH_QL_PARAM_FEATURE: featureId
      GRAPH_QL_PARAM_OPTION: optionId
      BASE_URL: https://999.md
      SEARCH_URL: "https://999.md/ro/list/transport/
      cars?appl=1&ef=16,1,6,2200&eo=12885,12900,12912,139,35538&aof=20&o_1_2095_8_98=36188"
      CAR_BRAND: Renault
      CAR_MODEL: Megane
    ports:
      - "8080:8080"

volumes:
  http_pgdata: