version: "3.9"

services:
  db:
    image: postgres:15
    container_name: selenium-postgres-db
    restart: always
    environment:
      POSTGRES_DB: selenium_scraper_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - selenium_pgdata:/var/lib/postgresql/data
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql

  selenium-chrome:
    image: selenium/standalone-chrome:latest
    container_name: selenium-chrome
    ports:
      - "4444:4444"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4444/status" ]
      interval: 5s
      timeout: 5s
      retries: 10

  selenium-firefox:
    image: selenium/standalone-firefox:latest
    container_name: selenium-firefox
    ports:
      - "4445:4444"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4444/status" ]
      interval: 5s
      timeout: 5s
      retries: 10

  scraper-app:
    build:
      context: .
    container_name: selenium-webscraper-app
    depends_on:
      selenium-chrome:
        condition: service_healthy
      selenium-firefox:
        condition: service_healthy
    environment:
      DATASOURCE_URL: jdbc:postgresql://db:5432/selenium_scraper_db
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: pass
      BASE_URL: https://999.md
      CAR_BRAND: Renault
      CAR_MODEL: Megane
      CAR_GENERATION: III (2008 - 2016)
      BROWSER_CHOICE: Firefox
      SELENIUM_CHROME_URL: http://selenium-chrome:4444/wd/hub
      SELENIUM_FIREFOX_URL: http://selenium-firefox:4444/wd/hub
    ports:
      - "8080:8080"
    volumes:
      - /dev/shm:/dev/shm

volumes:
  selenium_pgdata:
