version: "3.9"

services:
  db:
    image: postgres:15
    container_name: http-postgres-db
    restart: always
    environment:
      POSTGRES_DB: scraper_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  scraper-app:
    build:
      context: .
    container_name: http-webscraper-app
    depends_on:
      - db
    environment:
      DATASOURCE_URL: jdbc:postgresql://db:5432/scraper_db
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: pass
    ports:
      - "8080:8080"

volumes:
  pgdata: