version: "3.9"

services:
  db:
    image: postgres:15
    container_name: selenium-postgres-db
    restart: always
    environment:
      POSTGRES_DB: selenium_scraper_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - selenium_pgdata:/var/lib/postgresql/data
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql

  scraper-app:
    build:
      context: .
      target: selenium
    container_name: selenium-webscraper-app
    depends_on:
      - db
    environment:
      DATASOURCE_URL: jdbc:postgresql://db:5432/selenium_scraper_db
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: pass
      FIREFOX_BIN: /usr/bin/firefox-esr
      BASE_URL: https://999.md
      CAR_BRAND: Renault
      CAR_MODEL: Megane
      CAR_GENERATION: III (2008 - 2016)
      BROWSER_CHOICE: Firefox
    ports:
      - "8080:8080"
    volumes:
      - /dev/shm:/dev/shm

volumes:
  selenium_pgdata:
