version: "3.9"

services:
  db:
    image: postgres:15
    container_name: playwright-postgres-db
    restart: always
    environment:
      POSTGRES_DB: scraper_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  scraper-app:
    build:
      context: .
      target: playwright
    container_name: playwright-webscraper-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/scraper_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: pass
    ports:
      - "8080:8080"
    volumes:
      - /dev/shm:/dev/shm

volumes:
  pgdata: