version: "3.9"

services:
  db:
    image: postgres:15
    container_name: playwright-postgres-db
    restart: always
    environment:
      POSTGRES_DB: playwright_scraper_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - playwright_data:/var/lib/postgresql/data
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql

  scraper-app:
    build:
      context: .
      target: playwright
    container_name: playwright-webscraper-app
    depends_on:
      - db
    environment:
      DATASOURCE_URL: jdbc:postgresql://db:5432/playwright_scraper_db
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: pass
      BASE_URL: https://999.md
      CAR_BRAND: Renault
      CAR_MODEL: Megane
      CAR_GENERATION: III (2008 - 2016)
      BROWSER_CHOICE: Firefox
    ports:
      - "8080:8080"
    volumes:
      - /dev/shm:/dev/shm

volumes:
  playwright_data: